export const API_URL = "https://ill-bear-gown.cyclic.app"
//export const API_URL = "http://localhost:3001"
export const TOKEN_KEY = "USELL_TOKEN"
export const LOGGINED_USER="USER"
export const LOGGINED_ADMIN="ADMIN"